### ISSUE TITLE
[Q] Adding custom function

### ISSUE THREAD

**Issue by rdcm** [graphite-project/graphite-web#2687]
Hi!

I'm trying to add a custom function to graphite as described in the documentation, and after all steps added function not displayed in grafana.
https://graphite.readthedocs.io/en/latest/functions.html#function-plugins

`docker-compose.yml`:

```
version: '3.6'

services:
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - graphite_data:/opt/graphite/storage
      - ./to_upper.py:/opt/graphite/webapp/graphite/functions/custom/to_upper.py
    networks:
      - dev

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on:
      - graphite
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - dev

networks:
  dev:
    name: dev
    driver: bridge

volumes:
  grafana_data:
    name: grafana_data

  graphite_data:
    name: graphite_data
```

`to_upper.py`:
```
from graphite.functions.params import Param, ParamTypes

def toUpperCase(requestContext, seriesList):
  """Custom function that changes series names to UPPERCASE"""
  for series in seriesList:
    series.name = series.name.upper()
  return seriesList

toUpperCase.group = 'Custom'
toUpperCase.params = [
  Param('seriesList', ParamTypes.seriesList, required=True),
]

SeriesFunctions = {
  'upper': toUpperCase,
}
```

As mentioned in the documentation:
```
Custom plugin files may be placed in the /opt/graphite/webapp/graphite/functions/custom folder and will be loaded automatically when graphite starts.
```

Should I explicitly adding my function to `FUNCTION_PLUGINS`?

Thanks.
